In [2]:
import sqlite3
import requests
import time
import json
import pandas as pd
import urllib.parse

In [3]:
DB_PATH = 'gaming_warehouse.db'

In [4]:
#Crear la tabla de hsitorico de reviews
def preparar_tabla_reviews():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS RAW_Steam_Reviews (
            resena_id TEXT PRIMARY KEY,
            juego_id INTEGER,
            resena_texto TEXT,
            recomendado INTEGER, -- (voted_up)
            votos_utiles INTEGER, -- (votes_up)
            votos_graciosos INTEGER, -- (votes_funny)
            puntuacion_ponderada REAL, -- (weighted_vote_score)
            minutos_al_resenar INTEGER, -- (playtime_at_review)
            minutos_totales INTEGER, -- (playtime_forever)
            fecha_creacion_unix INTEGER, -- (timestamp_created)
            autor_num_resenas INTEGER,
            autor_num_juegos INTEGER,
            recibido_gratis INTEGER,
            escrito_acceso_anticipado INTEGER,
            FOREIGN KEY(juego_id) REFERENCES CAT_Juego(juego_id)
        );
    """)
    conn.commit()
    conn.close()

In [5]:
preparar_tabla_reviews()

In [6]:
#Nota: Ver como limitar y tener cuudado con el autocompeltado ya que pone nombres a cosas y me condunde
#Corregir nombre a los esparado
conn = sqlite3.connect(DB_PATH)
cursor = conn.cursor()
cursor.execute("ALTER TABLE RAW_Steam_Reviews RENAME TO Hist_Steam_Reviews;")
conn.commit()
conn.close()

OperationalError: there is already another table or index with this name: Hist_Steam_Reviews

In [7]:
# descargoi las reviews pero estableci apraemtros que la primer version quiso desacrgar todo
# max_reviews_por_juego: Limite máximo de reseñas a descargar por juego.
# min_reviews_juego: Número mínimo de reseñas que debe tener un juego para ser procesado porque hay algunos con pocas reviews.
# limite_juegos: Número máximo de juegos a procesar pro ejecucion.
def descargar_reviews_steam(max_reviews_por_juego=100, min_reviews_juego=20, limite_juegos=10):
    conn = sqlite3.connect(DB_PATH)
    query = """
        SELECT juego_id, id_steam, titulo, recommendations_count 
        FROM CAT_Juego 
        WHERE id_steam IS NOT NULL 
          AND recommendations_count >= ? 
          AND steam_price_final IS NOT NULL
        ORDER BY recommendations_count DESC
        LIMIT ?
    """
    juegos = pd.read_sql_query(query, conn, params=(min_reviews_juego, limite_juegos))
    conn.close()

    if juegos.empty:
        print("No se encontraron juegos con los criterios especificados.")
        return

    total_juegos = len(juegos)
    print(f"Inicio {total_juegos} juegos")

# ciclo para descargar las reseñas de cada juego, con paginacion y control de errores
    for i, (_, juego) in enumerate(juegos.iterrows(), 1):
        appid = juego['id_steam']
        juego_id = juego['juego_id']
        reviews_objetivo = min(max_reviews_por_juego, juego['recommendations_count'])
        reviews_acumuladas = 0
        cursor = '*'
        
        print(f"\n[{i}/{total_juegos}] Procesando: {juego['titulo']} (AppID: {appid})")
        print(f"Objetivo: {reviews_objetivo} reseñas.")

        #paginacion para descargar las rseñas en lotes
        while reviews_acumuladas < max_reviews_por_juego:
            cursor_encoded = urllib.parse.quote(cursor)
            url = f"https://store.steampowered.com/appreviews/{appid}?json=1&filter=all&language=spanish&purchase_type=all&cursor={cursor_encoded}&num_per_page=100"
            
            try:
                res = requests.get(url)
                if res.status_code != 200:
                    print(f"Error HTTP {res.status_code}.")
                    break
                
                data = res.json()
                if not data.get('success') or not data.get('reviews'):
                    print("no hay mas resanas")
                    break

                batch = data['reviews']
                insert_data = []
                
                #Guardar mis datos esperados
                for r in batch:
                    insert_data.append((
                        str(r['recommendationid']),
                        juego_id,
                        r['review'],
                        1 if r['voted_up'] else 0,
                        r['votes_up'],
                        r['votes_funny'],
                        float(r['weighted_vote_score']),
                        r['author']['playtime_at_review'],
                        r['author']['playtime_forever'],
                        r['timestamp_created'],
                        r['author']['num_reviews'],
                        r['author']['num_games_owned'],
                        1 if r['received_for_free'] else 0,
                        1 if r['written_during_early_access'] else 0
                    ))

                conn = sqlite3.connect(DB_PATH)
                db_cursor = conn.cursor()
                db_cursor.executemany(f"""
                    INSERT OR IGNORE INTO Hist_Steam_Reviews 
                    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
                """, insert_data)
                
                nuevas = db_cursor.rowcount
                conn.commit()
                conn.close()

                reviews_acumuladas += len(batch)
                
                print(f"  > Lote procesado: {len(batch)} obtenidas | {nuevas} nuevas en BD. (Total: {reviews_acumuladas})")

                cursor = data.get('cursor')
                
                if len(batch) < 100:
                    print("  > Se alcanzó el final de las reseñas disponibles.")
                    break
                
                time.sleep(1)

            except Exception as e:
                print(f"Error inesperado: {e}")
                break

In [ ]:
descargar_reviews_steam(max_reviews_por_juego=2000, min_reviews_juego=20, limite_juegos=6544)

Inicio 5520 juegos

[1/5520] Procesando: Counter-Strike 2 (AppID: 730)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 39 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 36 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 47 nuevas en BD. (Total: 800)
  > Lote procesado: 100 obtenidas | 92 nuevas en BD. (Total: 900)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1000)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1100)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1200)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1300)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1400)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1500)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1800)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1900)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 2000)

[2/5520] Procesando: PUBG: Battlegrounds (AppID: 578080)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 49 obtenidas | 0 nuevas en BD. (Total: 249)
  > Se alcanzó el final de las reseñas disponibles.

[3/5520] Procesando: Rainbow Six Siege (AppID: 359550)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 14 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 59 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 68 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 63 nuevas en BD. (Total: 400)
  > Lote procesado: 11 obtenidas | 7 nuevas en BD. (Total: 411)
  > Se alcanzó el final de las reseñas disponibles.

[4/5520] Procesando: Terraria (AppID: 105600)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 22 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 74 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 800)
  > Lote procesado: 66 obtenidas | 66 nuevas en BD. (Total: 866)
  > Se alcanzó el final de las reseñas disponibles.

[5/5520] Procesando: Rust (AppID: 252490)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 37 obtenidas | 0 nuevas en BD. (Total: 337)
  > Se alcanzó el final de las reseñas disponibles.

[6/5520] Procesando: Garry's Mod (AppID: 4000)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 1 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 1 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 48 nuevas en BD. (Total: 600)
  > Lote procesado: 33 obtenidas | 33 nuevas en BD. (Total: 633)
  > Se alcanzó el final de las reseñas disponibles.

[7/5520] Procesando: Black Myth: Wukong (AppID: 2358720)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 26 obtenidas | 0 nuevas en BD. (Total: 126)
  > Se alcanzó el final de las reseñas disponibles.

[8/5520] Procesando: Stardew Valley (AppID: 413150)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 8 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 1 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 36 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 700)
  > Lote procesado: 21 obtenidas | 21 nuevas en BD. (Total: 721)
  > Se alcanzó el final de las reseñas disponibles.

[9/5520] Procesando: Cyberpunk 2077 (AppID: 1091500)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 54 obtenidas | 0 nuevas en BD. (Total: 354)
  > Se alcanzó el final de las reseñas disponibles.

[10/5520] Procesando: Helldivers 2 (AppID: 553850)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 7 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 400)
  > Lote procesado: 52 obtenidas | 0 nuevas en BD. (Total: 452)
  > Se alcanzó el final de las reseñas disponibles.

[11/5520] Procesando: Elden Ring (AppID: 1245620)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 400)
  > Lote procesado: 3 obtenidas | 0 nuevas en BD. (Total: 403)
  > Se alcanzó el final de las reseñas disponibles.

[12/5520] Procesando: The Witcher 3: Wild Hunt (AppID: 292030)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 5 nuevas en BD. (Total: 100)
  > Lote procesado: 63 obtenidas | 0 nuevas en BD. (Total: 163)
  > Se alcanzó el final de las reseñas disponibles.

[13/5520] Procesando: Red Dead Redemption 2 (AppID: 1174180)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 7 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 6 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 42 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 99 nuevas en BD. (Total: 700)
  > Lote procesado: 11 obtenidas | 11 nuevas en BD. (Total: 711)
  > Se alcanzó el final de las reseñas disponibles.

[14/5520] Procesando: Left 4 Dead 2 (AppID: 550)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 28 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 800)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 900)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1000)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1100)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1200)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1300)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1400)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1500)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1800)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1900)
  > Lote procesado: 54 obtenidas | 54 nuevas en BD. (Total: 1954)
  > Se alcanzó el final de las reseñas disponibles.

[15/5520] Procesando: Euro Truck Simulator 2 (AppID: 227300)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 28 obtenidas | 0 nuevas en BD. (Total: 328)
  > Se alcanzó el final de las reseñas disponibles.

[16/5520] Procesando: Baldur's Gate III (AppID: 1086940)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 200)
  > Lote procesado: 12 obtenidas | 0 nuevas en BD. (Total: 212)
  > Se alcanzó el final de las reseñas disponibles.

[17/5520] Procesando: Phasmophobia (AppID: 739630)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 8 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 8 nuevas en BD. (Total: 200)
  > Lote procesado: 68 obtenidas | 9 nuevas en BD. (Total: 268)
  > Se alcanzó el final de las reseñas disponibles.

[18/5520] Procesando: Dead by Daylight (AppID: 381210)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 6 nuevas en BD. (Total: 400)
  > Lote procesado: 63 obtenidas | 2 nuevas en BD. (Total: 463)
  > Se alcanzó el final de las reseñas disponibles.

[19/5520] Procesando: Among Us (AppID: 945360)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 7 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 7 nuevas en BD. (Total: 300)
  > Lote procesado: 11 obtenidas | 0 nuevas en BD. (Total: 311)
  > Se alcanzó el final de las reseñas disponibles.

[20/5520] Procesando: Ark: Survival Evolved (AppID: 346110)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 20 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 200)
  > Lote procesado: 97 obtenidas | 2 nuevas en BD. (Total: 297)
  > Se alcanzó el final de las reseñas disponibles.

[21/5520] Procesando: The Forest (AppID: 242760)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 54 obtenidas | 11 nuevas en BD. (Total: 554)
  > Se alcanzó el final de las reseñas disponibles.

[22/5520] Procesando: Geometry Dash (AppID: 322170)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 14 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 14 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 10 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 10 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 69 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 800)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 900)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1000)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1100)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1200)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1300)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1400)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 1500)
  > Lote procesado: 24 obtenidas | 24 nuevas en BD. (Total: 1524)
  > Se alcanzó el final de las reseñas disponibles.

[23/5520] Procesando: Hollow Knight (AppID: 367520)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 48 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 700)
  > Lote procesado: 36 obtenidas | 36 nuevas en BD. (Total: 736)
  > Se alcanzó el final de las reseñas disponibles.

[24/5520] Procesando: Valheim (AppID: 892970)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 100)
  > Lote procesado: 47 obtenidas | 3 nuevas en BD. (Total: 147)
  > Se alcanzó el final de las reseñas disponibles.

[25/5520] Procesando: Payday 2 (AppID: 218620)
Objetivo: 2000 reseñas.
  > Lote procesado: 96 obtenidas | 7 nuevas en BD. (Total: 96)
  > Se alcanzó el final de las reseñas disponibles.

[26/5520] Procesando: Call of Duty (AppID: 1938090)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 18 obtenidas | 0 nuevas en BD. (Total: 318)
  > Se alcanzó el final de las reseñas disponibles.

[27/5520] Procesando: Lethal Company (AppID: 1966720)
Objetivo: 2000 reseñas.
  > Lote procesado: 96 obtenidas | 0 nuevas en BD. (Total: 96)
  > Se alcanzó el final de las reseñas disponibles.

[28/5520] Procesando: Portal 2 (AppID: 620)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 7 nuevas en BD. (Total: 100)
  > Lote procesado: 67 obtenidas | 2 nuevas en BD. (Total: 167)
  > Se alcanzó el final de las reseñas disponibles.

[29/5520] Procesando: DayZ (AppID: 221100)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 6 nuevas en BD. (Total: 100)
  > Lote procesado: 48 obtenidas | 1 nuevas en BD. (Total: 148)
  > Se alcanzó el final de las reseñas disponibles.

[30/5520] Procesando: Dying Light (AppID: 239140)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 70 obtenidas | 0 nuevas en BD. (Total: 270)
  > Se alcanzó el final de las reseñas disponibles.

[31/5520] Procesando: Hollow Knight: Silksong (AppID: 1030300)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 3 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 2 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 1 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 4 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 45 nuevas en BD. (Total: 600)
  > Lote procesado: 32 obtenidas | 32 nuevas en BD. (Total: 632)
  > Se alcanzó el final de las reseñas disponibles.

[32/5520] Procesando: Don't Starve Together (AppID: 322330)
Objetivo: 2000 reseñas.
  > Lote procesado: 74 obtenidas | 0 nuevas en BD. (Total: 74)
  > Se alcanzó el final de las reseñas disponibles.

[33/5520] Procesando: BeamNG.drive (AppID: 284160)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 54 obtenidas | 0 nuevas en BD. (Total: 154)
  > Se alcanzó el final de las reseñas disponibles.

[34/5520] Procesando: Palworld (AppID: 1623730)
Objetivo: 2000 reseñas.
  > Lote procesado: 87 obtenidas | 2 nuevas en BD. (Total: 87)
  > Se alcanzó el final de las reseñas disponibles.

[35/5520] Procesando: The Binding of Isaac: Rebirth (AppID: 250900)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 87 obtenidas | 0 nuevas en BD. (Total: 387)
  > Se alcanzó el final de las reseñas disponibles.

[36/5520] Procesando: Bloons TD 6 (AppID: 960090)
Objetivo: 2000 reseñas.
  > Lote procesado: 72 obtenidas | 2 nuevas en BD. (Total: 72)
  > Se alcanzó el final de las reseñas disponibles.

[37/5520] Procesando: Project Zomboid (AppID: 108600)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 29 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 32 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 800)
  > Lote procesado: 66 obtenidas | 66 nuevas en BD. (Total: 866)
  > Se alcanzó el final de las reseñas disponibles.

[38/5520] Procesando: Sea of Thieves (AppID: 1172620)
Objetivo: 2000 reseñas.
  > Lote procesado: 36 obtenidas | 2 nuevas en BD. (Total: 36)
  > Se alcanzó el final de las reseñas disponibles.

[39/5520] Procesando: Raft (AppID: 648800)
Objetivo: 2000 reseñas.
  > Lote procesado: 93 obtenidas | 2 nuevas en BD. (Total: 93)
  > Se alcanzó el final de las reseñas disponibles.

[40/5520] Procesando: Monster Hunter: World (AppID: 582010)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 6 nuevas en BD. (Total: 100)
  > Lote procesado: 17 obtenidas | 2 nuevas en BD. (Total: 117)
  > Se alcanzó el final de las reseñas disponibles.

[41/5520] Procesando: Subnautica (AppID: 264710)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 1 obtenidas | 0 nuevas en BD. (Total: 201)
  > Se alcanzó el final de las reseñas disponibles.

[42/5520] Procesando: No Man's Sky (AppID: 275850)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 40 obtenidas | 0 nuevas en BD. (Total: 140)
  > Se alcanzó el final de las reseñas disponibles.

[43/5520] Procesando: R.E.P.O. (AppID: 3241660)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 100)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 200)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 300)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 400)
  > Lote procesado: 100 obtenidas | 0 nuevas en BD. (Total: 500)
  > Lote procesado: 100 obtenidas | 23 nuevas en BD. (Total: 600)
  > Lote procesado: 100 obtenidas | 68 nuevas en BD. (Total: 700)
  > Lote procesado: 100 obtenidas | 100 nuevas en BD. (Total: 800)
  > Lote procesado: 21 obtenidas | 21 nuevas en BD. (Total: 821)
  > Se alcanzó el final de las reseñas disponibles.

[44/5520] Procesando: Deep Rock Galactic (AppID: 548430)
Objetivo: 2000 reseñas.
  > Lote procesado: 83 obtenidas | 8 nuevas en BD. (Total: 83)
  > Se alcanzó el final de las reseñas disponibles.

[45/5520] Procesando: People Playground (AppID: 1118200)
Objetivo: 2000 reseñas.
  > Lote procesado: 74 obtenidas | 1 nuevas en BD. (Total: 74)
  > Se alcanzó el final de las reseñas disponibles.

[46/5520] Procesando: Undertale (AppID: 391540)
Objetivo: 2000 reseñas.
  > Lote procesado: 100 obtenidas | 20 nuevas en BD. (Total: 100)

In [ ]:
def resumen_final_reviews(cantidad_top=10):
    conn = sqlite3.connect(DB_PATH)
    query = """
    SELECT 
        j.titulo,
        COUNT(r.resena_id) AS total_resenas_descargadas,
        ROUND(AVG(r.recomendado) * 100, 2) || '%' AS recomendado,
        ROUND(AVG(r.minutos_totales / 60.0), 1) AS promedio_horas_jugadas
    FROM Hist_Steam_Reviews r
    JOIN CAT_Juego j ON r.juego_id = j.juego_id
    GROUP BY j.juego_id
    ORDER BY total_resenas_descargadas DESC
    LIMIT ?;
    """
    df = pd.read_sql_query(query, conn, params=(cantidad_top,))
    conn.close()
    
    display(df)

In [ ]:
resumen_final_reviews(50)

,titulo,total_resenas_descargadas,recomendado,promedio_horas_jugadas
0,Terraria,503,96.62%,146.9
1,Counter-Strike 2,501,69.46%,583.9
2,Garry's Mod,501,98.4%,78.8
3,EA Sports FC 26,500,50.0%,86.4
4,Mewgenics,500,97.2%,88.2
5,Crimson Desert,500,99.6%,59.8
6,Schedule I,500,96.4%,43.7
7,R.E.P.O.,500,95.4%,43.5
8,Resident Evil Requiem,500,99.8%,37.4
9,Project Zomboid,500,95.4%,197.0
10,Geometry Dash,500,91.8%,140.4
11,Hollow Knight: Silksong,500,96.8%,75.2
12,Call of Duty: Modern Warfare,500,88.8%,13.7
13,Resident Evil 3,500,92.2%,12.7
14,Resident Evil 4,500,99.6%,49.8
15,Left 4 Dead 2,500,97.4%,216.7
16,Resident Evil 2,500,98.8%,24.8
17,Stardew Valley,500,99.2%,109.7
18,Undertale,500,55.4%,13.8
19,Hollow Knight,500,98.6%,64.3
20,Red Dead Redemption 2,500,98.4%,96.2
21,Grand Theft Auto V Enhanced,491,94.91%,90.9
22,The Forest,470,95.32%,32.1
23,ARC Raiders,445,86.97%,161.8
24,Ultrakill,418,97.61%,48.5
25,Resident Evil 4,413,97.34%,30.9
26,Marathon,367,91.01%,63.8
27,The Binding of Isaac: Rebirth,362,97.51%,214.7
28,Dead by Daylight,355,91.55%,265.7
29,Detroit: Become Human,340,98.82%,18.4
30,Cyberpunk 2077,331,96.68%,85.1
31,Helldivers 2,298,89.93%,166.1
32,Battlefield 1,294,91.16%,41.0
33,Euro Truck Simulator 2,292,98.63%,92.7
34,Among Us,287,95.12%,40.1
35,Plants vs. Zombies: Garden Warfare,285,97.54%,40.9
36,Sons of the Forest,283,92.58%,34.2
37,Rust,280,85.36%,646.9
38,Elden Ring,247,96.36%,145.2
39,Resident Evil Village,243,99.18%,25.3
40,Resident Evil 5,243,89.71%,24.1
41,Halo: The Master Chief Collection,237,97.89%,56.8
42,Dispatch,221,96.83%,14.4
43,Blasphemous,221,98.19%,32.6
44,Cuphead,219,97.26%,38.9
45,Resident Evil 6,215,84.19%,23.6
46,Phasmophobia,214,97.66%,79.0
47,Crisol: Theater of Idols,213,95.31%,16.1
48,The Crew: Motorfest,207,83.09%,29.3
49,Ark: Survival Evolved,206,87.86%,249.5

In [ ]:
def inspeccionar_resenas(busqueda, es_id=False):
    conn = sqlite3.connect(DB_PATH)
    
    if es_id:
        filtro = "j.juego_id = ?"
        parametro = busqueda
    else:
        filtro = "j.titulo LIKE ?"
        parametro = f"%{busqueda}%"

    query = f"""
    SELECT 
        j.juego_id,
        j.titulo,
        r.recomendado,
        r.minutos_totales / 60 AS horas_jugadas,
        r.votos_utiles,
        r.resena_texto
    FROM Hist_Steam_Reviews r
    JOIN CAT_Juego j ON r.juego_id = j.juego_id
    WHERE {filtro}
    --ORDER BY r.votos_utiles DESC
    --LIMIT 10;
    """
    
    df = pd.read_sql_query(query, conn, params=(parametro,))
    conn.close()
    
    if df.empty:
        print(f"No se encontraron reseñas para: {busqueda}")
    else:
        display(df)

In [ ]:
#Ara que tratar de alguna forma las malas palabras de los jeugos ya que se ve que son creativos con las opiniones
inspeccionar_resenas("lego")

,juego_id,titulo,recomendado,horas_jugadas,votos_utiles,resena_texto
0,1095,LEGO Star Wars: The Skywalker Saga,1,92,9,"92 horas después y con el 100% completado, pue..."
1,1095,LEGO Star Wars: The Skywalker Saga,1,11,0,"Es un gran juego, buenos graficos, dinamicas y..."
2,1095,LEGO Star Wars: The Skywalker Saga,1,32,0,"Esta muy bien hecha la trilogia original, much..."
3,1095,LEGO Star Wars: The Skywalker Saga,1,55,0,"es muy diferente a los originales de play 2 , ..."
4,1095,LEGO Star Wars: The Skywalker Saga,1,5,0,siempre los lego estan buenos pero prefiero ma...
...,...,...,...,...,...,...
261,1564,LEGO Indiana Jones 2: The Adventure Continues,1,18,0,"ESTA BIEN BUENO, LO PUTISIMO MALO ES QUE LA MI..."
262,1564,LEGO Indiana Jones 2: The Adventure Continues,1,17,0,clasicazo
263,3902,LEGO Harry Potter Collection,1,57,0,Obra maestra
264,4659,LEGO 2K Drive,1,26,0,"Esta muy guapo, el mundo es bastante grande y ..."
265,4659,LEGO 2K Drive,0,0,1,pobres crios si se ponen a jugar a esto... baz...

In [23]:
inspeccionar_resenas("pubg")

--- Mostrando reseñas más útiles para: PUBG: Battlegrounds ---

,juego_id,titulo,recomendado,horas_jugadas,votos_utiles,resena_texto
0,226,PUBG: Battlegrounds,1,320,0,"Excelente juego, mundo abierto y realista con ..."
1,226,PUBG: Battlegrounds,1,1087,0,"Me gusta el juego, siempre estan cambiando cos..."
2,226,PUBG: Battlegrounds,0,300,3,"Paso de jugar, es imposible con la cantidad de..."
3,226,PUBG: Battlegrounds,0,68,1,Imagina ser un muerto de hambre y sacar a la c...
4,226,PUBG: Battlegrounds,1,682,2,Gracias por poner la posibilidad de meter a un...
5,226,PUBG: Battlegrounds,1,2230,0,"Juego realista, mecanicas realistas, competiti..."
6,226,PUBG: Battlegrounds,1,687,0,este juego le dedique gran parte de mi vida ga...
7,226,PUBG: Battlegrounds,0,110,0,"Hace tiempo que tira error de ""Crash Unknow"" -..."
8,226,PUBG: Battlegrounds,1,710,0,ete juego esta chevere lo juego con mi pana de...
9,226,PUBG: Battlegrounds,0,5281,0,mierda de juego mal hecho cada ves que le mete...
10,226,PUBG: Battlegrounds,0,2371,1,"Bueno juego desde que salio el game, ya esta i..."
11,226,PUBG: Battlegrounds,1,677,0,Accion y depende de tu estilo te da la experie...
12,226,PUBG: Battlegrounds,0,7507,0,cheaters fpp 8.3.26 all cheaters all matches s...
13,226,PUBG: Battlegrounds,1,1026,0,para mi es el mejor juego y disfruto mucho jug...
14,226,PUBG: Battlegrounds,1,730,0,"es genial, llevo 8 años jugando a este tremend..."
15,226,PUBG: Battlegrounds,1,1035,0,muy bueno lastima los cheeters y
16,226,PUBG: Battlegrounds,1,16,0,es realista en aspecto de jugabilidad
17,226,PUBG: Battlegrounds,1,112,0,muy buen juego. lo recomiendo
18,226,PUBG: Battlegrounds,1,109,0,Bastante realista y bueno
19,226,PUBG: Battlegrounds,1,268,0,Excelent Game
20,226,PUBG: Battlegrounds,1,633,1,juegoql weno
21,226,PUBG: Battlegrounds,1,130,0,mejoro bastante
22,226,PUBG: Battlegrounds,1,107,0,si es muy bueno y dibertido
23,226,PUBG: Battlegrounds,1,261,1,Gran juego
24,226,PUBG: Battlegrounds,1,1391,0,mejor juego
25,226,PUBG: Battlegrounds,1,576,0,es arte\r\n
26,226,PUBG: Battlegrounds,1,48,0,Con audifonos
27,226,PUBG: Battlegrounds,0,6809,0,muchas cheats
28,226,PUBG: Battlegrounds,1,826,0,Good
29,226,PUBG: Battlegrounds,1,4903,0,malumabeibi
30,226,PUBG: Battlegrounds,1,2790,0,bueno
31,226,PUBG: Battlegrounds,1,900,0,ES BUENO
32,226,PUBG: Battlegrounds,1,3210,0,miua
33,226,PUBG: Battlegrounds,1,61,0,NACHI
34,226,PUBG: Battlegrounds,1,10,0,Si
35,226,PUBG: Battlegrounds,1,322,0,si
36,226,PUBG: Battlegrounds,1,355,0,:)